var data = {
    PayboxRemail: "negocioprueba1ppx@gmail.com",
    PayboxSendmail: "djegameryt@gmail.com",
    PayboxRename: "VendeYa",
    PayboxSendname: "VendeYa",
    PayboxBase0: "2.0",
    PayboxBase12: "10.0",
    PayboxDescription: "prueba",
    PayboxLanguage: "es",
    PayboxDirection: "av.francisco",
    PayBoxClientPhone: "0996309625",
    PayboxProduction: false,
    PayboxRecurrent: true,
    PayboxIdPlan: "171",
    PayboxPermitirCalendarizar: true,
    PayboxPagoInmediato: true,
    PayboxCobroPrueba: false,
    PayBoxClientIdentification: "0950316760",
    PayboxEnvironment: "sandbox",
    PayboxAmountVariablePlan: true,
    PayboxFrequencyPlan: "MEN",
    PayboxTieneIvaPlan: true,
    PayboxDescriptionPlan: "Descripcion plan",
    PayboxPagoPlux: false,
    PayboxEvento: "Evento descuento uno",
    PayboxOnlyCredit: true,
    PayboxOnlyDebit: true,
    PayboxIdElement: "idElementoTest",
    PayboxExtras: "id de pedido",
    PayboxPermitirBloquearDiferimientos: true,
    PayboxPermitirDatosAdicionales: true
};